server:
  port: 7090
  servlet:
    context-path: /auth
jwt:
  auth:
    converter:
      resource-id: authenticationClientId
keycloak:
  realm: spring-boot-kc
  domain: 127.0.0.1:8081
  adminClientId: admin-cli
  adminClientSecret: #enter client secret here
  client: authenticationClientId
  urls:
    auth: https://${keycloak.domain}
spring:
  profile:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${keycloak.domain}/realms/${keycloak.realm}
