server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:\Users\boonl\OneDrive\Documents\uni shits\y4s2\fyp2\sample app\config-repo
          clone-on-start: true
  application:
    name: config-server
